version: '2'

services:
  proxy:
    image: abiosoft/caddy:0.9.5
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    restart: unless-stopped
    hostname: ${HOSTNAME}
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOSTNAME: ${HOSTNAME}

  meteor:
    image: fleetr/web
    restart: unless-stoppedi
    hostname: www.${HOSTNAME}
    environment:
     - ROOT_URL=https://${HOSTNAME}
     - MONGO_URL=mongodb://mongo:27017/fleetr
     - MONGO_OPLOG_URL=mongodb://mongo:27017/local?authSource=admin
     - MAIL_URL=smtp://no-reply%40fleetr.eu:Z5fLfOmW3oeU@mail.fleetr.eu:465
     - 'METEOR_SETTINGS={"mqttUrl" : "mqtt://mqtt:1883", "mqttClientId": "fleetr@prod"}'

  traccar:
    image: fleetr/traccar
    restart: unless-stopped
    hostname: traccar.${HOSTNAME}
    depends_on:
      - db
      - mqtt
    ports:
      - "5055:5055"
      - "5027:5027"

  db:
    image: postgres:9
    restart: unless-stopped
    hostname: db.${HOSTNAME}
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar@fleetr
    volumes:
      - /data/traccar/postgres/data:/var/lib/postgresql/data

  mqtt:
    image: greyarch/mosquitto
    restart: unless-stopped
    hostname: mqtt.${HOSTNAME}

  mongo:
    image: mongo:3
    restart: unless-stopped
    hostname: mongo.${HOSTNAME}
    command: --replSet rs0
    volumes:
      - /data/fleetr/mongo/data:/data/db

  processor:
    image: fleetr/processor
    restart: unless-stopped
    hostname: processor.${HOSTNAME}
    depends_on:
      - mongo
      - mqtt

  nominatim:
    image: fleetr/nominatim
    restart: unless-stopped
    hostname: nominatim.${HOSTNAME}

  pgweb:
    image: donnex/pgweb
    restart: unless-stopped
    hostname: pgweb.${HOSTNAME}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    hostname: mongo-express.${HOSTNAME}
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 'mongo'
      ME_CONFIG_BASICAUTH_PASSWORD: 'mongo@fleetr'
